name: Deploy to development

on:
  push:
    branches:
    - "**"
  workflow_dispatch:
  repository_dispatch:

concurrency: 
  group: development
  cancel-in-progress: true

jobs:
  build:
    uses: au2001/gitops-demo-app/.github/workflows/build.yml@main
    with:
      prefix: dev-
      environment: Development
