name: Build & Deploy to production

on:
  push:
    tags:
    - v*

  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string

  repository_dispatch:
    inputs:
      version:
        required: false
        type: string

jobs:
  prepare:
    name: Prepare deployment
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.version }}

    steps:
    - name: Compute variables
      id: vars
      run: |
        if [[ ! -z "${{ inputs.version }}" ]]; then
          version="${{ inputs.version }}"
        elif [[ $GITHUB_REF == refs/tags/* ]]; then
          version=${GITHUB_REF/refs\/tags\//}
        else
          version=${GITHUB_BASE_REF:-${GITHUB_REF#refs/*/}}
        fi

        echo ::set-output name=version::$version

  build:
    needs: prepare
    uses: au2001/gitops-demo-app/.github/workflows/build.yml@main
    environment: production
    with:
      version: ${{ needs.prepare.outputs.version }}
      prefix: prd-
