name: Build & Deploy to staging

on:
  push:
  workflow_dispatch:
  repository_dispatch:

concurrency: 
  group: staging
  cancel-in-progress: true

jobs:
  build:
    uses: au2001/gitops-demo-app/.github/workflows/build.yml@main
    with:
      prefix: stg-
      environment: Staging
