name: Build & Deploy to staging

on:
  push:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    uses: au2001/gitops-demo-app/.github/workflows/build.yml@main
    environment: staging
    with:
      prefix: stg-
