name: Deploy to testing

on:
  workflow_dispatch:
  repository_dispatch:

concurrency: 
  group: testing
  cancel-in-progress: true

jobs:
  build:
    uses: au2001/gitops-demo-app/.github/workflows/build.yml@main
    with:
      prefix: tst-
      environment: Testing
